[features]
seeds = false
skip-lint = false
[programs.localnet]
coinflip_bet = "4SmSWTXY3MXgXW35rRfvfgEpZLASPeAbFcF87kyqjhNu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/andy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
