[features]
seeds = false
skip-lint = false
[programs.localnet]
coinflip_bet = "Ae1cbcDnNocF6yUSzMTr4wsMZDwhkj8sHfnM9ScYASn2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
